version: '2'
services:
  graphite:
    image: hopsoft/graphite-statsd
    restart: always
    ports:
      - '3001:80'
      - '2003-2004:2003-2004'
      - '2023-2024:2023-2024'
      - '8125:8125/udp'
      - '8126:8126'
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - ./conf/grafana/grafana.db:/var/lib/grafana/grafana.db